const womenCl = [
  {
    id: 1,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w1.jpg",
    discount: null,
  },
  {
    id: 2,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: 60.0,
    img: "./tmp/w2.jpg",
    discount: 50,
  },
  {
    id: 3,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w3.jpg",
    discount: null,
  },
  {
    id: 4,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w4.jpg",
    discount: null,
  },
  {
    id: 5,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w5.jpg",
    discount: null,
  },
  {
    id: 6,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w6.jpg",
    discount: null,
  },
  {
    id: 7,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w7.jpg",
    discount: null,
  },
  {
    id: 8,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/w8.jpg",
    discount: null,
  },
];

const menCl = [
  {
    id: 1,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m1.jpg",
    discount: null,
  },
  {
    id: 2,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m2.jpg",
    discount: null,
  },
  {
    id: 3,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m3.jpg",
    discount: null,
  },
  {
    id: 4,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m4.jpg",
    discount: null,
  },
  {
    id: 5,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m5.jpg",
    discount: null,
  },
  {
    id: 6,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m6.jpg",
    discount: null,
  },
  {
    id: 7,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m7.jpg",
    discount: null,
  },
  {
    id: 8,
    title: "Women's tracksuit Q109",
    price: 30.0,
    rate: 4,
    oldPrice: null,
    img: "./tmp/m8.jpg",
    discount: null,
  },
];

module.exports = { womenCl, menCl };
